language: python
sudo: false
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing Qiita in it's own environment python2.7
  - travis_retry conda create --yes -n qiita_env python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita_env
  - pip install sphinx sphinx-bootstrap-theme coveralls ipython[all]==2.4.1
  - pip install https://github.com/biocore/qiita/archive/master.zip --process-dependency-links
  - export MOI_CONFIG_FP=$HOME/miniconda3/envs/qiita_env/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg
  - ipython profile create qiita-general --parallel
  - qiita-env start_cluster qiita-general
  - qiita-env make --no-load-ontologies
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita_env/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  - source deactivate
  # installing this plugin
  - conda create --yes -n qiime2 python=$PYTHON_VERSION --file https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-conda-linux-64.txt
  - source activate qiime2
  - pip install coveralls
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install https://github.com/qiita-spots/qiita-files/archive/master.zip
  - travis_retry pip install .
before_script:
  - source activate qiita_env
  - qiita pet webserver start &
  - sleep 10 # give enough time to the webserver to start
script:
  - source activate qiime2
  - configure_qiime2 --env-script "source activate qiime2" --server-cert $QIITA_SERVER_CERT
  - nosetests --with-doctest --with-coverage --cover-package=qp_qiime2
  - flake8 qp_qiime2 setup.py scripts
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - coveralls
