dist: precise
language: python
sudo: false
env:
  - PYTHON_VERSION=3.6
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  # installing Qiita in it's own environment python3.6
  - travis_retry conda create -q --yes -n qiita python=3.6 pip libgfortran numpy nginx cython
  - source activate qiita
  - pip install -U pip
  - pip install sphinx sphinx-bootstrap-theme coveralls
  - pip install https://github.com/biocore/qiita/archive/dev.zip --no-binary redbiom
  # as we don't need redbiom we are going to use the default redis port
  - sed 's/PORT = 7777/PORT = 6379/g' $HOME/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test.cfg
  # starting nginx
  - mkdir /home/travis/miniconda3/envs/qiita/var/run/nginx/
  - wget https://github.com/biocore/qiita/archive/dev.zip -O qiita-dev.zip
  - unzip qiita-dev.zip
  - nginx -c ${PWD}/qiita-dev/qiita_pet/nginx_example.conf
  - qiita-env make --no-load-ontologies
  - source deactivate
  # installing this plugin
  - wget -q https://data.qiime2.org/distro/core/qiime2-2020.6-py36-linux-conda.yml
  - travis_retry conda env create -q -n qiime2 --file qiime2-2020.6-py36-linux-conda.yml
  - rm qiime2-2020.6-py36-linux-conda.yml
  - source activate qiime2
  - qiime info
  - pip install coveralls flake8
  # we are going to use the same qiime2 environment to install qtp-diversity
  - pip install https://github.com/qiita-spots/qtp-diversity/archive/master.zip
  # we are going to use the same qiime2 environment to install qtp-visualization
  - pip install https://github.com/qiita-spots/qtp-visualization/archive/master.zip
  - travis_retry pip install .
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/server.crt
  - configure_diversity_types --env-script "source ~/virtualenv/python2.7/bin/activate; export PATH=$HOME/miniconda3/bin/:$PATH; . activate qiime2" --server-cert $QIITA_SERVER_CERT
  - configure_visualization_types --env-script "source ~/virtualenv/python2.7/bin/activate; export PATH=$HOME/miniconda3/bin/:$PATH; . activate qiime2" --server-cert $QIITA_SERVER_CERT
  - mkdir databases
  - wget -O "databases/gg-13-8-99-515-806-nb-classifier.qza" "https://data.qiime2.org/2020.6/common/gg-13-8-99-515-806-nb-classifier.qza"
  - export QP_QIIME2_DBS=${PWD}/databases
  - configure_qiime2 --env-script "export QP_QIIME2_DBS=${PWD}/databases;source ~/virtualenv/python2.7/bin/activate; export PATH=$HOME/miniconda3/bin/:$PATH; . activate qiime2" --server-cert $QIITA_SERVER_CERT
before_script:
  - source activate qiita
  - qiita plugins update
  - supervisord -c ${PWD}/qiita-dev/qiita_pet/supervisor_example.conf
  - sleep 10 # give enough time to the webserver to start
  - cat /tmp/supervisord.log
script:
  - source activate qiime2
  - export QP_QIIME2_DBS=${PWD}/databases
  - start_diversity_types https://localhost:8383 register ignored
  - start_visualization_types https://localhost:8383 register ignored
  # Remove the SubjectAltNameWarning from the output
  - export PYTHONWARNINGS="ignore:Certificate for localhost has no \`subjectAltName\`"
  - nosetests --with-doctest --with-coverage --cover-package=qp_qiime2
  - flake8 qp_qiime2 setup.py scripts
addons:
  postgresql: "9.5"
services:
  - redis-server
  - postgresql
after_success:
  - coveralls
